# Generated by Django 6.0.3 on 2026-03-11 22:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Legal company name', max_length=255)),
                ('dba_name', models.CharField(blank=True, default='', help_text='Doing Business As name', max_length=255)),
                ('phone', models.CharField(blank=True, default='', max_length=20)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('website', models.URLField(blank=True, default='')),
                ('address_line1', models.CharField(blank=True, default='', max_length=255)),
                ('address_line2', models.CharField(blank=True, default='', max_length=255)),
                ('city', models.CharField(blank=True, default='', max_length=100)),
                ('state', models.CharField(blank=True, default='', max_length=2)),
                ('zip_code', models.CharField(blank=True, default='', max_length=20)),
                ('tax_id', models.CharField(blank=True, default='', help_text='EIN or Tax ID', max_length=20)),
                ('usdot_number', models.CharField(blank=True, default='', help_text='USDOT number if applicable', max_length=20)),
                ('logo', models.ImageField(blank=True, help_text='Company logo', null=True, upload_to='company/logos/')),
                ('settings', models.JSONField(blank=True, default=dict, help_text='Company-wide settings and preferences')),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Company',
                'db_table': 'company',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Department name', max_length=100, unique=True)),
                ('code', models.CharField(help_text="Short department code (e.g., 'SRV', 'INSP')", max_length=20, unique=True)),
                ('description', models.TextField(blank=True, default='', help_text='Department description and responsibilities')),
                ('is_active', models.BooleanField(default=True, help_text='Whether department is currently active')),
                ('allows_floating', models.BooleanField(default=True, help_text='Whether employees from other departments can float to this department')),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
                'db_table': 'departments',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee_number', models.CharField(help_text='Unique employee number/ID', max_length=20, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('phone', models.CharField(blank=True, default='', max_length=20)),
                ('title', models.CharField(blank=True, default='', help_text='Job title', max_length=100)),
                ('hire_date', models.DateField(blank=True, help_text='Date of hire', null=True)),
                ('termination_date', models.DateField(blank=True, help_text='Date of termination (if applicable)', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether employee is currently active')),
                ('certifications', models.JSONField(blank=True, default=list, help_text='List of certifications (e.g., ASE, CDL)')),
                ('skills', models.JSONField(blank=True, default=list, help_text='List of skills and specializations')),
                ('settings', models.JSONField(blank=True, default=dict, help_text='Employee preferences and settings')),
                ('base_department', models.ForeignKey(help_text='Primary/home department', on_delete=django.db.models.deletion.PROTECT, related_name='base_employees', to='organization.department')),
                ('floating_departments', models.ManyToManyField(blank=True, help_text='Additional departments employee can work in', related_name='floating_employees', to='organization.department')),
                ('user', models.OneToOneField(blank=True, help_text='Django user account (if employee has system access)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Employees',
                'db_table': 'employees',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.AddField(
            model_name='department',
            name='manager',
            field=models.ForeignKey(blank=True, help_text='Department manager/supervisor', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_departments', to='organization.employee'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['base_department', 'is_active'], name='employees_base_de_f0bc91_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['employee_number'], name='employees_employe_68f2c7_idx'),
        ),
    ]
