# Generated by Django 6.0.3 on 2026-03-11 20:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('title', models.CharField(blank=True, help_text='Job title', max_length=100)),
                ('email', models.EmailField(blank=True, help_text='Email address', max_length=254)),
                ('phone', models.CharField(blank=True, help_text='Primary phone', max_length=50)),
                ('phone_extension', models.CharField(blank=True, help_text='Extension', max_length=20)),
                ('mobile', models.CharField(blank=True, help_text='Mobile/cell phone', max_length=50)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_automated', models.BooleanField(default=False, help_text='Contact is an automated system (API, email processor, webhook, etc.)')),
                ('receive_invoices', models.BooleanField(default=False, help_text='Receives invoices and billing statements')),
                ('receive_estimates', models.BooleanField(default=False, help_text='Receives quotes and estimates')),
                ('receive_service_updates', models.BooleanField(default=False, help_text='Receives work order and inspection updates')),
                ('receive_inspection_reports', models.BooleanField(default=False, help_text='Receives inspection reports and compliance notifications')),
                ('notes', models.TextField(blank=True, help_text='Notes about this contact')),
            ],
            options={
                'db_table': 'contacts',
                'ordering': ['customer', 'last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, help_text='Business name (DBA)', max_length=255)),
                ('legal_name', models.CharField(blank=True, help_text='Legal registered name', max_length=255)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('address_line1', models.CharField(blank=True, max_length=255)),
                ('address_line2', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, help_text='US state code', max_length=2)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('country', models.CharField(default='US', help_text='ISO country code', max_length=2)),
                ('usdot_number', models.CharField(blank=True, db_index=True, default='', help_text='US DOT Number', max_length=20)),
                ('mc_number', models.CharField(blank=True, db_index=True, default='', help_text='Motor Carrier Number', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Internal notes about this customer')),
                ('primary_contact', models.ForeignKey(blank=True, help_text='Primary contact for this customer', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_for_customers', to='customers.contact')),
            ],
            options={
                'db_table': 'customers',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='contact',
            name='customer',
            field=models.ForeignKey(help_text='Customer organization this contact belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='customers.customer'),
        ),
        migrations.CreateModel(
            name='USDOTProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('usdot_number', models.CharField(db_index=True, help_text='US DOT Number', max_length=20)),
                ('mc_number', models.CharField(blank=True, help_text='Motor Carrier Number', max_length=20)),
                ('legal_name', models.CharField(blank=True, max_length=255)),
                ('dba_name', models.CharField(blank=True, help_text='Doing Business As', max_length=255)),
                ('entity_type', models.CharField(blank=True, help_text='LLC, Corporation, etc.', max_length=100)),
                ('physical_address', models.CharField(blank=True, max_length=500)),
                ('physical_city', models.CharField(blank=True, max_length=100)),
                ('physical_state', models.CharField(blank=True, max_length=2)),
                ('physical_zip', models.CharField(blank=True, max_length=20)),
                ('mailing_address', models.CharField(blank=True, max_length=500)),
                ('mailing_city', models.CharField(blank=True, max_length=100)),
                ('mailing_state', models.CharField(blank=True, max_length=2)),
                ('mailing_zip', models.CharField(blank=True, max_length=20)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('carrier_operation', models.CharField(blank=True, help_text='Interstate, Intrastate', max_length=100)),
                ('cargo_carried', models.TextField(blank=True, help_text='Types of cargo')),
                ('operation_classification', models.JSONField(blank=True, default=list, help_text='Authorized For Hire, Private, etc.')),
                ('safety_rating', models.CharField(blank=True, max_length=50)),
                ('out_of_service_date', models.DateField(blank=True, null=True)),
                ('total_power_units', models.IntegerField(blank=True, null=True)),
                ('total_drivers', models.IntegerField(blank=True, null=True)),
                ('raw_fmcsa_data', models.JSONField(blank=True, help_text='Complete FMCSA API response for reference', null=True)),
                ('lookup_date', models.DateTimeField(auto_now=True, help_text='Last time FMCSA data was fetched')),
                ('customer', models.OneToOneField(help_text='Customer this profile belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='usdot_profile', to='customers.customer')),
            ],
            options={
                'db_table': 'usdot_profiles',
            },
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['is_active', 'name'], name='customers_is_acti_45534e_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['usdot_number'], name='customers_usdot_n_b10204_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['mc_number'], name='customers_mc_numb_7188cb_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['primary_contact'], name='customers_primary_c52ed9_idx'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['customer', 'is_active'], name='contacts_custome_fa85cb_idx'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['email'], name='contacts_email_2eb381_idx'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['is_automated'], name='contacts_is_auto_90bbb9_idx'),
        ),
        migrations.AddIndex(
            model_name='usdotprofile',
            index=models.Index(fields=['usdot_number'], name='usdot_profi_usdot_n_c3e708_idx'),
        ),
        migrations.AddIndex(
            model_name='usdotprofile',
            index=models.Index(fields=['mc_number'], name='usdot_profi_mc_numb_4d6f76_idx'),
        ),
    ]
