# Generated by Django 6.0.3 on 2026-03-11 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usdotprofile',
            name='mailing_address',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='usdotprofile',
            name='mailing_city',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='usdotprofile',
            name='mailing_state',
            field=models.CharField(blank=True, default='', max_length=2),
        ),
        migrations.AlterField(
            model_name='usdotprofile',
            name='mailing_zip',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='usdotprofile',
            name='physical_address',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='usdotprofile',
            name='physical_city',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='usdotprofile',
            name='physical_state',
            field=models.CharField(blank=True, default='', max_length=2),
        ),
        migrations.AlterField(
            model_name='usdotprofile',
            name='physical_zip',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
