# Generated by Django 6.0.3 on 2026-03-12 18:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_alter_usdotprofile_mailing_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usdotprofile',
            name='customer',
            field=models.OneToOneField(blank=True, help_text='Customer this profile belongs to (null until customer is created)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usdot_profile', to='customers.customer'),
        ),
    ]
