# Generated by Django 6.0.3 on 2026-03-16 18:26

from django.contrib.postgres.operations import TrigramExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_add_user_to_contact'),
    ]

    operations = [
        # Enable PostgreSQL trigram extension for fuzzy text matching
        TrigramExtension(),
    ]
