# Generated by Django 6.0.3 on 2026-03-16 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_enable_pg_trgm'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='last_selected_at',
            field=models.DateTimeField(blank=True, help_text='Last time this customer was selected', null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='selection_count',
            field=models.IntegerField(db_index=True, default=0, help_text='Number of times this customer has been selected (for ranking duplicate detection results)'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['-selection_count'], name='customers_selecti_4ca821_idx'),
        ),
    ]
