# Generated by Django 6.0.3 on 2026-03-16 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0006_add_duplicate_detection_fields'),
    ]

    operations = [
        # Add GIN indexes for trigram fuzzy search on text fields
        # These indexes enable fast similarity() queries using pg_trgm
        migrations.RunSQL(
            sql="""
            CREATE INDEX customers_name_gin_trgm_idx ON customers USING gin (name gin_trgm_ops);
            CREATE INDEX customers_legal_name_gin_trgm_idx ON customers USING gin (legal_name gin_trgm_ops);
            """,
            reverse_sql="""
            DROP INDEX IF EXISTS customers_name_gin_trgm_idx;
            DROP INDEX IF EXISTS customers_legal_name_gin_trgm_idx;
            """,
        ),
    ]
