# Generated by Django 6.0.3 on 2026-03-11 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '__first__'),
        ('work_orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='assigned_employees',
            field=models.ManyToManyField(blank=True, help_text='Employees assigned to this work order', related_name='assigned_work_orders', to='organization.employee'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='departments',
            field=models.ManyToManyField(blank=True, help_text='Departments involved in this work order', related_name='work_orders', to='organization.department'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='assigned_to',
            field=models.CharField(blank=True, help_text='Legacy: Technician name or ID (use assigned_employees instead)', max_length=200),
        ),
    ]
