# Generated by Django 6.0.3 on 2026-03-12 12:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
        ('work_orders', '0002_workorder_assigned_employees_workorder_departments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='approval_status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_APPROVAL', 'Pending Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='DRAFT', help_text='Approval status for work order', max_length=20),
        ),
        migrations.AddField(
            model_name='workorder',
            name='approved_at',
            field=models.DateTimeField(blank=True, help_text='When work order was approved', null=True),
        ),
        migrations.AddField(
            model_name='workorder',
            name='approved_by',
            field=models.ForeignKey(blank=True, help_text='Employee who approved this work order', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_work_orders', to='organization.employee'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='rejected_reason',
            field=models.TextField(blank=True, help_text='Reason for rejection if approval_status is REJECTED'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='source_id',
            field=models.UUIDField(blank=True, help_text='UUID of source object (defect, maintenance task, etc.)', null=True),
        ),
        migrations.AddField(
            model_name='workorder',
            name='source_type',
            field=models.CharField(choices=[('INSPECTION_DEFECT', 'Inspection Defect'), ('MAINTENANCE_SCHEDULE', 'Maintenance Schedule'), ('CUSTOMER_REQUEST', 'Customer Request'), ('BREAKDOWN', 'Breakdown'), ('MANUAL', 'Manual')], default='MANUAL', help_text='Type of source that created this work order', max_length=30),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='source',
            field=models.CharField(choices=[('INSPECTION', 'Inspection'), ('CUSTOMER_REQUEST', 'Customer Request'), ('PM_SCHEDULE', 'PM Schedule'), ('BREAKDOWN', 'Breakdown')], default='CUSTOMER_REQUEST', help_text='Legacy: How this work order originated (use source_type instead)', max_length=30),
        ),
        migrations.CreateModel(
            name='WorkOrderLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('line_number', models.IntegerField(help_text='Line number for ordering (1, 2, 3, ...)')),
                ('verb', models.CharField(help_text="Action verb (e.g., 'Replace', 'Inspect', 'Repair')", max_length=50)),
                ('noun', models.CharField(help_text="Component/part noun (e.g., 'Hydraulic Hose', 'Boom Cylinder')", max_length=100)),
                ('service_location', models.CharField(help_text="Service location (e.g., 'Boom Assembly', 'Chassis')", max_length=100)),
                ('description', models.TextField(help_text='Full description of task (auto-generated from vocabulary or manual)')),
                ('estimated_hours', models.DecimalField(blank=True, decimal_places=2, help_text='Estimated hours to complete this line', max_digits=5, null=True)),
                ('actual_hours', models.DecimalField(blank=True, decimal_places=2, help_text='Actual hours spent on this line', max_digits=5, null=True)),
                ('parts_required', models.JSONField(blank=True, default=list, help_text='List of part numbers/descriptions required')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING', help_text='Status of this line item', max_length=20)),
                ('completed_at', models.DateTimeField(blank=True, help_text='When this line was completed', null=True)),
                ('notes', models.TextField(blank=True, help_text='Notes specific to this line')),
                ('assigned_to', models.ForeignKey(blank=True, help_text='Employee assigned to this specific line', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_work_order_lines', to='organization.employee')),
                ('completed_by', models.ForeignKey(blank=True, help_text='Employee who completed this line', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_work_order_lines', to='organization.employee')),
                ('work_order', models.ForeignKey(help_text='Parent work order', on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='work_orders.workorder')),
            ],
            options={
                'verbose_name': 'Work Order Line',
                'verbose_name_plural': 'Work Order Lines',
                'db_table': 'work_order_lines',
                'ordering': ['work_order', 'line_number'],
                'indexes': [models.Index(fields=['work_order', 'line_number'], name='work_order__work_or_309f5e_idx'), models.Index(fields=['status'], name='work_order__status_0f8c71_idx'), models.Index(fields=['assigned_to'], name='work_order__assigne_71beb2_idx')],
                'unique_together': {('work_order', 'line_number')},
            },
        ),
    ]
