# Generated by Django 6.0.3 on 2026-03-12 12:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
        ('work_orders', '0003_workorder_approval_status_workorder_approved_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='department',
            field=models.ForeignKey(blank=True, help_text='Primary department assigned to this work order', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_work_orders', to='organization.department'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='due_date',
            field=models.DateField(blank=True, db_index=True, help_text='When work must be completed by', null=True),
        ),
        migrations.AddField(
            model_name='workorder',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether this work order is active (soft delete flag)'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='title',
            field=models.CharField(blank=True, default='', help_text='Brief title for work order', max_length=255),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='assigned_employees',
            field=models.ManyToManyField(blank=True, help_text='Legacy: Employees assigned to this work order (use WorkOrderLine.assigned_to instead)', related_name='assigned_work_orders', to='organization.employee'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='assigned_to',
            field=models.ForeignKey(blank=True, help_text='Primary employee assigned to this work order', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_assigned_work_orders', to='organization.employee'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='departments',
            field=models.ManyToManyField(blank=True, help_text='Legacy: Departments involved in this work order', related_name='work_orders', to='organization.department'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='priority',
            field=models.CharField(choices=[('LOW', 'Low'), ('NORMAL', 'Normal'), ('HIGH', 'High'), ('EMERGENCY', 'Emergency')], default='NORMAL', help_text='Priority level for scheduling and dispatch', max_length=20),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('ON_HOLD', 'On Hold'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], db_index=True, default='DRAFT', max_length=20),
        ),
    ]
