# Generated by Django 6.0.3 on 2026-03-12 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_orders', '0004_workorder_department_workorder_due_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorderline',
            name='blocks_operation',
            field=models.BooleanField(db_index=True, default=False, help_text='If true, this defect prevents safe operation (typically CRITICAL severity)'),
        ),
    ]
