# Generated by Django 6.0.3 on 2026-03-16 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_add_user_to_contact'),
        ('organization', '0001_initial'),
        ('work_orders', '0005_add_blocks_operation_to_work_order_line'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='workorder',
            name='work_orders_source__3544fb_idx',
        ),
        migrations.AlterField(
            model_name='workorder',
            name='department',
            field=models.ForeignKey(blank=True, help_text='Department assigned to this work order', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_work_orders', to='organization.department'),
        ),
        migrations.AddIndex(
            model_name='workorder',
            index=models.Index(fields=['source_type', 'source_id'], name='work_orders_source__a1ab34_idx'),
        ),
        migrations.RemoveField(
            model_name='workorder',
            name='assigned_employees',
        ),
        migrations.RemoveField(
            model_name='workorder',
            name='departments',
        ),
        migrations.RemoveField(
            model_name='workorder',
            name='source',
        ),
        migrations.RemoveField(
            model_name='workorder',
            name='source_inspection_run',
        ),
    ]
