# Generated by Django 6.0.3 on 2026-03-11 20:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InspectionRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset_type', models.CharField(choices=[('VEHICLE', 'Vehicle'), ('EQUIPMENT', 'Equipment')], help_text='Type of asset being inspected', max_length=20)),
                ('asset_id', models.UUIDField(help_text='UUID of Vehicle or Equipment being inspected')),
                ('template_key', models.CharField(db_index=True, help_text="Key of inspection template used (e.g., 'ansi_a92_2_periodic')", max_length=100)),
                ('program_key', models.CharField(blank=True, help_text="Inspection program this fulfills (e.g., 'ANSI_A92_2')", max_length=100)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed')], db_index=True, default='DRAFT', max_length=20)),
                ('started_at', models.DateTimeField(help_text='When inspection was started')),
                ('finalized_at', models.DateTimeField(blank=True, db_index=True, help_text='When inspection was finalized (becomes immutable)', null=True)),
                ('inspector_name', models.CharField(blank=True, help_text='Name of inspector performing inspection', max_length=200)),
                ('inspector_signature', models.JSONField(blank=True, help_text='Digital signature data: {signature_data, signed_at, signed_by, ip_address}', null=True)),
                ('template_snapshot', models.JSONField(help_text='Immutable copy of template at execution time')),
                ('step_data', models.JSONField(default=dict, help_text='Collected inspection data, keyed by module_key.step_key')),
                ('notes', models.TextField(blank=True, help_text='General notes about the inspection')),
                ('customer', models.ForeignKey(help_text='Customer who owns the asset (denormalized for queries)', on_delete=django.db.models.deletion.PROTECT, related_name='inspection_runs', to='customers.customer')),
            ],
            options={
                'verbose_name': 'Inspection Run',
                'verbose_name_plural': 'Inspection Runs',
                'db_table': 'inspection_runs',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='InspectionDefect',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('defect_identity', models.CharField(db_index=True, help_text='SHA256 hash for idempotency: run_id + module_key + step_key + rule_id', max_length=64, unique=True)),
                ('module_key', models.CharField(help_text="Module where defect was found (e.g., 'visual_inspection')", max_length=100)),
                ('step_key', models.CharField(help_text="Step where defect was found (e.g., 'hydraulic_leaks')", max_length=100)),
                ('rule_id', models.CharField(blank=True, help_text='Rule that generated this defect (null for manual defects)', max_length=100, null=True)),
                ('severity', models.CharField(choices=[('CRITICAL', 'Critical'), ('MAJOR', 'Major'), ('MINOR', 'Minor'), ('ADVISORY', 'Advisory')], db_index=True, help_text='CRITICAL: unsafe to operate, MAJOR: significant issue, MINOR: maintenance needed, ADVISORY: informational', max_length=20)),
                ('title', models.CharField(help_text='Short description of defect', max_length=500)),
                ('description', models.TextField(help_text='Detailed description of defect')),
                ('defect_details', models.JSONField(blank=True, help_text='Structured defect data: {location, photos, measurements, etc.}', null=True)),
                ('evaluation_trace', models.JSONField(blank=True, help_text='How this defect was generated: {rule_id, condition, evaluated_at, response_data}', null=True)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('WORK_ORDER_CREATED', 'Work Order Created'), ('RESOLVED', 'Resolved')], db_index=True, default='OPEN', max_length=30)),
                ('inspection_run', models.ForeignKey(help_text='Inspection that generated this defect', on_delete=django.db.models.deletion.CASCADE, related_name='defects', to='inspections.inspectionrun')),
            ],
            options={
                'verbose_name': 'Inspection Defect',
                'verbose_name_plural': 'Inspection Defects',
                'db_table': 'inspection_defects',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='inspectionrun',
            index=models.Index(fields=['asset_type', 'asset_id'], name='inspection__asset_t_fb2a1b_idx'),
        ),
        migrations.AddIndex(
            model_name='inspectionrun',
            index=models.Index(fields=['customer', 'status'], name='inspection__custome_ef379f_idx'),
        ),
        migrations.AddIndex(
            model_name='inspectionrun',
            index=models.Index(fields=['template_key'], name='inspection__templat_95dd4f_idx'),
        ),
        migrations.AddIndex(
            model_name='inspectionrun',
            index=models.Index(fields=['finalized_at'], name='inspection__finaliz_f3af03_idx'),
        ),
        migrations.AddIndex(
            model_name='inspectionrun',
            index=models.Index(fields=['started_at'], name='inspection__started_a9f31a_idx'),
        ),
        migrations.AddIndex(
            model_name='inspectiondefect',
            index=models.Index(fields=['inspection_run', 'severity'], name='inspection__inspect_9972ec_idx'),
        ),
        migrations.AddIndex(
            model_name='inspectiondefect',
            index=models.Index(fields=['status', 'severity'], name='inspection__status_5477e0_idx'),
        ),
        migrations.AddIndex(
            model_name='inspectiondefect',
            index=models.Index(fields=['module_key', 'step_key'], name='inspection__module__658d83_idx'),
        ),
    ]
