# Generated by Django 6.0.3 on 2026-03-11 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspectionrun',
            name='step_data',
            field=models.JSONField(blank=True, default=dict, help_text='Collected inspection data, keyed by module_key.step_key'),
        ),
    ]
