# Generated by Django 6.0.3 on 2026-03-12 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0002_alter_inspectionrun_step_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspectiondefect',
            name='module_key',
            field=models.CharField(blank=True, help_text="Module where defect was found (e.g., 'visual_inspection')", max_length=100),
        ),
    ]
