# Generated by Django 6.0.3 on 2026-03-14 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0003_alter_inspectiondefect_module_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspectiondefect',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Detailed description of defect'),
        ),
    ]
