# Generated by Django 6.0.3 on 2026-03-15 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0004_make_defect_description_optional'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspectionrun',
            name='inspection_outcome',
            field=models.CharField(blank=True, choices=[('PASS', 'Pass - Equipment safe for operation'), ('PASS_WITH_REPAIRS', 'Pass - Repairs required before next inspection'), ('FAIL', 'Fail - Equipment unsafe, tagged out of service')], db_index=True, help_text='Auto-calculated outcome based on defects and blocking failures', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='inspectionrun',
            name='outcome_summary',
            field=models.JSONField(blank=True, help_text='Summary data: defect counts by severity, blocking failures, etc.', null=True),
        ),
    ]
