# Generated by Django 6.0.3 on 2026-03-16 12:18

import apps.inspections.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0005_add_inspection_outcome'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InspectionPhoto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('step_key', models.CharField(db_index=True, help_text='Step where photo was captured', max_length=100)),
                ('image', models.ImageField(help_text='Original photo file', upload_to=apps.inspections.models.inspection_photo_upload_path)),
                ('thumbnail', models.ImageField(blank=True, help_text='Auto-generated thumbnail (300x300)', null=True, upload_to=apps.inspections.models.inspection_photo_upload_path)),
                ('caption', models.CharField(blank=True, help_text='Optional photo caption or description', max_length=255)),
                ('file_size', models.IntegerField(help_text='File size in bytes')),
                ('width', models.IntegerField(blank=True, help_text='Image width in pixels', null=True)),
                ('height', models.IntegerField(blank=True, help_text='Image height in pixels', null=True)),
                ('defect', models.ForeignKey(blank=True, help_text='Defect this photo is evidence for (optional)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='inspections.inspectiondefect')),
                ('inspection', models.ForeignKey(help_text='Inspection this photo belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='inspections.inspectionrun')),
                ('uploaded_by', models.ForeignKey(blank=True, help_text='User who uploaded the photo', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_inspection_photos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Inspection Photo',
                'verbose_name_plural': 'Inspection Photos',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['inspection', 'step_key'], name='inspections_inspect_3be317_idx'), models.Index(fields=['defect'], name='inspections_defect__7eb2d0_idx'), models.Index(fields=['inspection', 'created_at'], name='inspections_inspect_4ac94b_idx')],
            },
        ),
    ]
