# Generated by Django 6.0.3 on 2026-03-11 20:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vin', models.CharField(db_index=True, help_text='17-character Vehicle Identification Number', max_length=17, unique=True)),
                ('unit_number', models.CharField(blank=True, db_index=True, help_text="Customer's internal unit/fleet number", max_length=50)),
                ('license_plate', models.CharField(blank=True, help_text='Current license plate number', max_length=20)),
                ('year', models.IntegerField(blank=True, help_text='Model year', null=True)),
                ('make', models.CharField(blank=True, db_index=True, max_length=100)),
                ('model', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('odometer_miles', models.IntegerField(blank=True, help_text='Current odometer reading in miles', null=True)),
                ('engine_hours', models.IntegerField(blank=True, help_text='Current engine hour meter reading', null=True)),
                ('tags', models.JSONField(blank=True, default=list, help_text="Tags for inspection applicability (e.g., ['INSULATED_BOOM', 'DIELECTRIC'])")),
                ('notes', models.TextField(blank=True, help_text='Internal notes')),
                ('customer', models.ForeignKey(help_text='Customer that owns this vehicle', on_delete=django.db.models.deletion.PROTECT, related_name='vehicles', to='customers.customer')),
            ],
            options={
                'db_table': 'vehicles',
                'ordering': ['unit_number', '-year'],
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('serial_number', models.CharField(db_index=True, help_text='Manufacturer serial number', max_length=100, unique=True)),
                ('asset_number', models.CharField(blank=True, db_index=True, help_text="Customer's internal asset/equipment number", max_length=50)),
                ('equipment_type', models.CharField(blank=True, db_index=True, help_text='Aerial Device, Crane, Generator, Compressor, etc.', max_length=100)),
                ('manufacturer', models.CharField(blank=True, max_length=100)),
                ('model', models.CharField(blank=True, max_length=100)),
                ('year', models.IntegerField(blank=True, help_text='Manufacture year', null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('engine_hours', models.IntegerField(blank=True, help_text='Current engine/operation hour meter', null=True)),
                ('cycles', models.IntegerField(blank=True, help_text='Current cycle count (for equipment with cycle meters)', null=True)),
                ('tags', models.JSONField(blank=True, default=list, help_text="Tags for inspection applicability (e.g., ['AERIAL_DEVICE', 'INSULATED_BOOM', 'DIELECTRIC'])")),
                ('equipment_data', models.JSONField(blank=True, default=dict, help_text='Equipment-specific data: placard info, rated capacity, insulation class, etc.')),
                ('notes', models.TextField(blank=True, help_text='Internal notes')),
                ('customer', models.ForeignKey(help_text='Customer that owns this equipment', on_delete=django.db.models.deletion.PROTECT, related_name='equipment', to='customers.customer')),
                ('mounted_on_vehicle', models.ForeignKey(blank=True, help_text='Vehicle this equipment is mounted on (if applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipment', to='assets.vehicle')),
            ],
            options={
                'verbose_name_plural': 'equipment',
                'db_table': 'equipment',
                'ordering': ['asset_number', 'serial_number'],
            },
        ),
        migrations.CreateModel(
            name='VINDecodeData',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vin', models.CharField(db_index=True, help_text='VIN that was decoded', max_length=17)),
                ('model_year', models.IntegerField(blank=True, null=True)),
                ('make', models.CharField(blank=True, max_length=100)),
                ('model', models.CharField(blank=True, max_length=100)),
                ('manufacturer', models.CharField(blank=True, help_text='Full manufacturer name', max_length=200)),
                ('vehicle_type', models.CharField(blank=True, help_text='Truck, Trailer, Passenger Car, etc.', max_length=100)),
                ('body_class', models.CharField(blank=True, help_text='Cab & Chassis, Van, Pickup, etc.', max_length=100)),
                ('engine_model', models.CharField(blank=True, max_length=100)),
                ('engine_configuration', models.CharField(blank=True, max_length=50)),
                ('engine_cylinders', models.IntegerField(blank=True, null=True)),
                ('displacement_liters', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('fuel_type_primary', models.CharField(blank=True, help_text='Diesel, Gasoline, Electric, etc.', max_length=50)),
                ('fuel_type_secondary', models.CharField(blank=True, help_text='For dual-fuel vehicles', max_length=50)),
                ('gvwr', models.CharField(blank=True, help_text='Gross Vehicle Weight Rating', max_length=100)),
                ('gvwr_min_lbs', models.IntegerField(blank=True, help_text='GVWR minimum in pounds', null=True)),
                ('gvwr_max_lbs', models.IntegerField(blank=True, help_text='GVWR maximum in pounds', null=True)),
                ('abs', models.CharField(blank=True, help_text='Anti-lock Braking System', max_length=50)),
                ('airbag_locations', models.CharField(blank=True, max_length=200)),
                ('plant_city', models.CharField(blank=True, max_length=100)),
                ('plant_state', models.CharField(blank=True, max_length=100)),
                ('plant_country', models.CharField(blank=True, max_length=100)),
                ('error_code', models.CharField(blank=True, help_text='0 = success, other = error', max_length=10)),
                ('error_text', models.TextField(blank=True, help_text='Any error message from NHTSA')),
                ('decoded_at', models.DateTimeField(auto_now_add=True, help_text='When decode was performed')),
                ('raw_response', models.JSONField(blank=True, help_text='Complete raw JSON response from NHTSA for reference', null=True)),
                ('vehicle', models.OneToOneField(help_text='Vehicle this decode belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='vin_decode', to='assets.vehicle')),
            ],
            options={
                'verbose_name': 'VIN Decode Data',
                'verbose_name_plural': 'VIN Decode Data',
                'db_table': 'vin_decode_data',
                'ordering': ['-decoded_at'],
            },
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['customer', 'is_active'], name='vehicles_custome_1feb6d_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['vin'], name='vehicles_vin_42311c_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['unit_number'], name='vehicles_unit_nu_f6d65c_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['make', 'model'], name='vehicles_make_17021f_idx'),
        ),
        migrations.AddIndex(
            model_name='equipment',
            index=models.Index(fields=['customer', 'is_active'], name='equipment_custome_f7cb4f_idx'),
        ),
        migrations.AddIndex(
            model_name='equipment',
            index=models.Index(fields=['serial_number'], name='equipment_serial__ac559e_idx'),
        ),
        migrations.AddIndex(
            model_name='equipment',
            index=models.Index(fields=['asset_number'], name='equipment_asset_n_685c31_idx'),
        ),
        migrations.AddIndex(
            model_name='equipment',
            index=models.Index(fields=['equipment_type'], name='equipment_equipme_f4cc15_idx'),
        ),
        migrations.AddIndex(
            model_name='equipment',
            index=models.Index(fields=['mounted_on_vehicle'], name='equipment_mounted_da211d_idx'),
        ),
        migrations.AddIndex(
            model_name='vindecodedata',
            index=models.Index(fields=['vin'], name='vin_decode__vin_df1e9f_idx'),
        ),
        migrations.AddIndex(
            model_name='vindecodedata',
            index=models.Index(fields=['make', 'model'], name='vin_decode__make_dae42e_idx'),
        ),
        migrations.AddIndex(
            model_name='vindecodedata',
            index=models.Index(fields=['decoded_at'], name='vin_decode__decoded_735836_idx'),
        ),
    ]
