# Generated by Django 6.0.3 on 2026-03-11 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='capabilities',
            field=models.JSONField(blank=True, default=list, help_text="Equipment capabilities (e.g., ['INSULATING_SYSTEM', 'BARE_HAND_WORK_UNIT'])"),
        ),
    ]
