# Generated by Django 6.0.3 on 2026-03-12 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_add_capabilities_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='tags',
        ),
        migrations.AlterField(
            model_name='equipment',
            name='capabilities',
            field=models.JSONField(blank=True, default=list, help_text="Equipment capabilities and features (e.g., ['AERIAL_DEVICE', 'INSULATING_SYSTEM', 'BARE_HAND_WORK_UNIT'])"),
        ),
    ]
