# Generated by Django 6.0.3 on 2026-03-12 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_remove_tags_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='tags',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='capabilities',
            field=models.JSONField(blank=True, default=list, help_text="Vehicle capabilities and features (e.g., ['UTILITY_TRUCK', 'INSULATED_BOOM', 'DIELECTRIC'])"),
        ),
    ]
