# Generated by Django 6.0.3 on 2026-03-12 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0004_consolidate_to_capabilities'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='body_type',
            field=models.CharField(blank=True, choices=[('', 'Standard (No Special Body)'), ('AERIAL', 'Aerial Device (Bucket Truck)')], db_index=True, default='', help_text='Special body type if vehicle is incomplete/upfitted (only add types we have inspection templates for)', max_length=20),
        ),
    ]
