# Generated by Django 6.0.3 on 2026-03-12 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0005_add_vehicle_body_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='equipment_type',
            field=models.CharField(blank=True, choices=[('', 'Not Specified'), ('AERIAL_DEVICE', 'Aerial Device')], db_index=True, default='', help_text='Equipment type (only add types we have inspection templates for)', max_length=20),
        ),
    ]
