# Generated by Django 6.0.3 on 2026-03-13 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0006_change_equipment_type_to_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='photo',
            field=models.ImageField(blank=True, help_text='Equipment photo for quick identification', null=True, upload_to='assets/equipment/'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='photo',
            field=models.ImageField(blank=True, help_text='Vehicle photo for quick identification', null=True, upload_to='assets/vehicles/'),
        ),
    ]
