# Generated by Django 6.0.3 on 2026-03-13 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0007_equipment_photo_vehicle_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='body_class',
            field=models.CharField(blank=True, help_text="Body class from VIN decode (e.g., 'Cab & Chassis', 'Van', 'Pickup')", max_length=100),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='vehicle_type',
            field=models.CharField(blank=True, help_text="Vehicle type from VIN decode (e.g., 'Truck', 'Incomplete Vehicle', 'Trailer')", max_length=100),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='body_type',
            field=models.CharField(blank=True, choices=[('', 'None / As Delivered'), ('SERVICE', 'Service Body'), ('FLATBED', 'Flatbed'), ('STAKE', 'Stake Body'), ('DUMP', 'Dump Body'), ('VAN', 'Van Body'), ('BOX', 'Box/Cargo Body'), ('REFUSE', 'Refuse Body'), ('TANK', 'Tank Body'), ('CRANE', 'Crane Body'), ('TOW', 'Tow/Wrecker Body'), ('UTILITY', 'Utility Body'), ('OTHER', 'Other')], db_index=True, default='', help_text='Type of body installed on the vehicle (if any)', max_length=20),
        ),
    ]
