# Generated by Django 6.0.3 on 2026-03-13 17:56

from django.db import migrations, models


def migrate_aerial_device_to_a92_2(apps, schema_editor):
    """Migrate existing AERIAL_DEVICE equipment to A92_2_AERIAL."""
    Equipment = apps.get_model('assets', 'Equipment')
    Equipment.objects.filter(equipment_type='AERIAL_DEVICE').update(equipment_type='A92_2_AERIAL')


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0008_add_vehicle_type_body_class_update_body_type_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='equipment_type',
            field=models.CharField(blank=True, choices=[('', 'Not Specified'), ('A92_2_AERIAL', 'Aerial Device (ANSI A92.2 - Vehicle-Mounted Elevating & Rotating)'), ('A92_20_SCISSOR', 'Scissor Lift (ANSI A92.20 - Self-Propelled)'), ('A92_20_BOOM', 'Boom Lift (ANSI A92.20 - Self-Propelled)'), ('A92_3_VERTICAL', 'Vertical Mast Lift (ANSI A92.3 - Manually Propelled)'), ('B30_5_CRANE', 'Mobile/Locomotive Crane (ANSI/ASME B30.5)'), ('B30_22_ARTICULATING', 'Articulating Boom Crane (ANSI/ASME B30.22)'), ('DIGGER_DERRICK', 'Digger Derrick'), ('FORKLIFT', 'Forklift'), ('GENERATOR', 'Generator'), ('COMPRESSOR', 'Air Compressor'), ('WELDER', 'Welder'), ('CRANE_BOOM_TRUCK', 'Crane/Boom Truck')], db_index=True, default='', help_text='Equipment type aligned with applicable inspection standards (ANSI/ASME/OSHA)', max_length=30),
        ),
        migrations.RunPython(migrate_aerial_device_to_a92_2, migrations.RunPython.noop),
    ]
