# Generated by Django 5.2.12 on 2026-03-11 18:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('inspections', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('work_order_number', models.CharField(db_index=True, help_text="Auto-generated work order number (e.g., 'WO-2025-00123')", max_length=50, unique=True)),
                ('asset_type', models.CharField(choices=[('VEHICLE', 'Vehicle'), ('EQUIPMENT', 'Equipment')], help_text='Type of asset being serviced', max_length=20)),
                ('asset_id', models.UUIDField(help_text='UUID of Vehicle or Equipment being serviced')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SCHEDULED', 'Scheduled'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], db_index=True, default='DRAFT', max_length=20)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='MEDIUM', help_text='Priority level for scheduling and dispatch', max_length=20)),
                ('source', models.CharField(choices=[('INSPECTION', 'Inspection'), ('CUSTOMER_REQUEST', 'Customer Request'), ('PM_SCHEDULE', 'PM Schedule'), ('BREAKDOWN', 'Breakdown')], help_text='How this work order originated', max_length=30)),
                ('description', models.TextField(help_text='Description of work to be performed')),
                ('scheduled_date', models.DateField(blank=True, db_index=True, help_text='When work is scheduled to be performed', null=True)),
                ('assigned_to', models.CharField(blank=True, help_text='Technician name or ID assigned to this work', max_length=200)),
                ('started_at', models.DateTimeField(blank=True, help_text='When work was actually started', null=True)),
                ('completed_at', models.DateTimeField(blank=True, db_index=True, help_text='When work was completed', null=True)),
                ('odometer_at_service', models.IntegerField(blank=True, help_text='Vehicle odometer reading when service was performed (miles)', null=True)),
                ('engine_hours_at_service', models.IntegerField(blank=True, help_text='Equipment engine hours when service was performed', null=True)),
                ('notes', models.TextField(blank=True, help_text='General notes about the work order')),
                ('customer', models.ForeignKey(help_text='Customer who owns the asset', on_delete=django.db.models.deletion.PROTECT, related_name='work_orders', to='customers.customer')),
                ('source_inspection_run', models.ForeignKey(blank=True, help_text='Link to inspection if source is INSPECTION', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_orders', to='inspections.inspectionrun')),
            ],
            options={
                'verbose_name': 'Work Order',
                'verbose_name_plural': 'Work Orders',
                'db_table': 'work_orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkOrderDefect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linked_at', models.DateTimeField(auto_now_add=True, help_text='When this link was created')),
                ('defect', models.ForeignKey(help_text='Defect being addressed by this work order', on_delete=django.db.models.deletion.CASCADE, related_name='work_order_links', to='inspections.inspectiondefect')),
                ('work_order', models.ForeignKey(help_text='Work order that addresses this defect', on_delete=django.db.models.deletion.CASCADE, related_name='defect_links', to='work_orders.workorder')),
            ],
            options={
                'verbose_name': 'Work Order Defect Link',
                'verbose_name_plural': 'Work Order Defect Links',
                'db_table': 'work_order_defects',
            },
        ),
        migrations.AddIndex(
            model_name='workorder',
            index=models.Index(fields=['customer', 'status'], name='work_orders_custome_a5db79_idx'),
        ),
        migrations.AddIndex(
            model_name='workorder',
            index=models.Index(fields=['asset_type', 'asset_id'], name='work_orders_asset_t_5eb4b4_idx'),
        ),
        migrations.AddIndex(
            model_name='workorder',
            index=models.Index(fields=['source_inspection_run'], name='work_orders_source__3544fb_idx'),
        ),
        migrations.AddIndex(
            model_name='workorder',
            index=models.Index(fields=['scheduled_date'], name='work_orders_schedul_a0bdce_idx'),
        ),
        migrations.AddIndex(
            model_name='workorder',
            index=models.Index(fields=['status', 'priority'], name='work_orders_status_d07f78_idx'),
        ),
        migrations.AddIndex(
            model_name='workorder',
            index=models.Index(fields=['completed_at'], name='work_orders_complet_732507_idx'),
        ),
        migrations.AddIndex(
            model_name='workorderdefect',
            index=models.Index(fields=['work_order'], name='work_order__work_or_cce0ca_idx'),
        ),
        migrations.AddIndex(
            model_name='workorderdefect',
            index=models.Index(fields=['defect'], name='work_order__defect__8ff026_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='workorderdefect',
            unique_together={('work_order', 'defect')},
        ),
    ]
